# this is a basic workflow to help you get started with Actions
#!/usr/bin/env bash
name: company

# Controls when the workflow will run
on:
# Triggers the workflow on push or pull requets events but only for the 'main' branch
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

# Allows you to run this workflow manually from the Actions tab
 workflow_dispatch:

# A workflow run is made up of one more jobs that can run sequentialy or in parallel
jobs:
  # This workflow contains a simple job called "build"
  build:
    # the type of runner that the job will run on
    runs-on: ubuntu-lastest

    # Steps represent a sequense of task that will be executed as part of the job
    steps:
      # Check-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Runs a single command using the runners shell
      - name: Step 1 check version Newmman and Node
        run:
            newman --version
            node --version
      
      # Runs a set of command using the runner shell
      - name: Step 2 Install Newman-Reporter-Htmlextra
        run: sudo npm install -g newman-reporter-htmlextra

        # Runs a set of commands using the runners shell
      - name: Step 3 Execute collection
        run: newman run ./Company_success.json -g ./globals.json -e ./Postman.json --delay-requet 1 --reporters cli, -r htmlextra --reporter-htmlextra-export ./result/Report.html

        # Runs a set of commands using the runners shell
      - name: Step 4 Archive production artifacts
        uses: actions/upload-artifacts@v3
        with:
              name: report
              path: ./result/Report.html
